### ISSUE TITLE
Installation via composer

### ISSUE THREAD

**Issue by hafizchin** [apaoww/yii2-oci8#1]
Hi,
I can't seem to install your plugin using the installation guide.

For your reference, I've attached a screenshot of the error.

![composer apaoww yii2-oci8](https://cloud.githubusercontent.com/assets/6478018/7677148/51cf6d5c-fd7c-11e4-90b2-f3c2c36051f4.PNG)

Thanks,

**Comment by apaoww** [comment]
Hi,

This plugin it still in development but ready to used. You can use "dev-master" instead of "~1.0"

by using this command 

php composer.phar require apaoww/yii2-oci8 "dev-master"

It still new in writing yii2 plugin. I don't know how to set packagist.org to minimum-stability. I'm still learning.

So just use dev-master should be okay. I already try.
